### ISSUE TITLE
Use github releases

### ISSUE THREAD

**Issue by Ivoah** [gameblabla/pocketsnes-nspire#1]
Move the zip from the main repo to using GitHub releases.

**Comment by gameblabla** [comment]
Done.
Honestly, i don't see any use for now because i want to always to link to the latest version
and i don't want to confuse users even more.

**Comment by mzomparelli** [comment]
If you don't use GitHub releases then how do we know if we need to update? When your code is stable you should release. Any commits not in a release are still being tested or waiting for the need to create another release. I thought about it like you. I wanted everyone to just have the latest build. Sometimes it is difficult for a user to know if they have the version that is your recent build. It's much easier on the user if you release properly.
